-- Conecta - Modularizacao (V057): administracao completa (modulos core e tecnologia) para os perfis de TI.
-- Aditiva e idempotente: so insere o que falta e registra em modularizacao_grants_log. Gerada de
-- rh_api/repositories/modulos_schema.py.

IF OBJECT_ID('dbo.modularizacao_grants_log', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.modularizacao_grants_log (
        id_perfil NVARCHAR(40) NOT NULL,
        chave_permissao NVARCHAR(120) NOT NULL,
        migration NVARCHAR(20) NOT NULL,
        criado_em DATETIME NOT NULL CONSTRAINT DF_modularizacao_grants_log_criado_em DEFAULT GETDATE(),
        CONSTRAINT PK_modularizacao_grants_log PRIMARY KEY (id_perfil, chave_permissao, migration)
    );
END;

IF OBJECT_ID('dbo.perfil_permissoes', 'U') IS NOT NULL AND OBJECT_ID('dbo.permissoes', 'U') IS NOT NULL
BEGIN
    INSERT INTO dbo.perfil_permissoes (id_perfil, chave_permissao, permitido, criado_em, atualizado_em)
    OUTPUT INSERTED.id_perfil, INSERTED.chave_permissao, 'V057', GETDATE()
        INTO dbo.modularizacao_grants_log (id_perfil, chave_permissao, migration, criado_em)
    SELECT v.id_perfil, v.chave, 1, GETDATE(), GETDATE()
    FROM (VALUES
        ('tecnico_junior', 'configuracoes.editar'),
        ('tecnico_junior', 'configuracoes.visualizar'),
        ('tecnico_junior', 'dashboard.visualizar'),
        ('tecnico_junior', 'documentos_biblioteca.editar'),
        ('tecnico_junior', 'documentos_biblioteca.visualizar'),
        ('tecnico_junior', 'inicio.visualizar'),
        ('tecnico_junior', 'lgpd.anonimizar'),
        ('tecnico_junior', 'lgpd.configurar'),
        ('tecnico_junior', 'lgpd.exportar_dados'),
        ('tecnico_junior', 'logs.exportar'),
        ('tecnico_junior', 'logs.visualizar'),
        ('tecnico_junior', 'mural.criar'),
        ('tecnico_junior', 'mural.editar'),
        ('tecnico_junior', 'mural.excluir'),
        ('tecnico_junior', 'mural.visualizar'),
        ('tecnico_junior', 'notificacoes.configurar'),
        ('tecnico_junior', 'notificacoes.visualizar'),
        ('tecnico_junior', 'onboarding.concluir_proprio'),
        ('tecnico_junior', 'onboarding.editar'),
        ('tecnico_junior', 'onboarding.visualizar'),
        ('tecnico_junior', 'operacoes.editar'),
        ('tecnico_junior', 'operacoes.visualizar'),
        ('tecnico_junior', 'relatorios.exportar'),
        ('tecnico_junior', 'relatorios.visualizar'),
        ('tecnico_junior', 'sessao.configuracoes.acessar'),
        ('tecnico_junior', 'sessao.drive.acessar'),
        ('tecnico_junior', 'sessao.gestao.acessar'),
        ('tecnico_junior', 'sessao.treinamentos.acessar'),
        ('tecnico_junior', 'usuarios.alterar_email'),
        ('tecnico_junior', 'usuarios.alterar_perfil'),
        ('tecnico_junior', 'usuarios.ativar'),
        ('tecnico_junior', 'usuarios.bloquear'),
        ('tecnico_junior', 'usuarios.criar'),
        ('tecnico_junior', 'usuarios.desativar'),
        ('tecnico_junior', 'usuarios.desbloquear'),
        ('tecnico_junior', 'usuarios.editar'),
        ('tecnico_junior', 'usuarios.excluir'),
        ('tecnico_junior', 'usuarios.redefinir_senha'),
        ('tecnico_junior', 'usuarios.ver_logs'),
        ('tecnico_junior', 'usuarios.visualizar'),
        ('tecnico_pleno', 'configuracoes.editar'),
        ('tecnico_pleno', 'configuracoes.visualizar'),
        ('tecnico_pleno', 'dashboard.visualizar'),
        ('tecnico_pleno', 'documentos_biblioteca.editar'),
        ('tecnico_pleno', 'documentos_biblioteca.visualizar'),
        ('tecnico_pleno', 'inicio.visualizar'),
        ('tecnico_pleno', 'lgpd.anonimizar'),
        ('tecnico_pleno', 'lgpd.configurar'),
        ('tecnico_pleno', 'lgpd.exportar_dados'),
        ('tecnico_pleno', 'logs.exportar'),
        ('tecnico_pleno', 'logs.visualizar'),
        ('tecnico_pleno', 'mural.criar'),
        ('tecnico_pleno', 'mural.editar'),
        ('tecnico_pleno', 'mural.excluir'),
        ('tecnico_pleno', 'mural.visualizar'),
        ('tecnico_pleno', 'notificacoes.configurar'),
        ('tecnico_pleno', 'notificacoes.visualizar'),
        ('tecnico_pleno', 'onboarding.concluir_proprio'),
        ('tecnico_pleno', 'onboarding.editar'),
        ('tecnico_pleno', 'onboarding.visualizar'),
        ('tecnico_pleno', 'operacoes.editar'),
        ('tecnico_pleno', 'operacoes.visualizar'),
        ('tecnico_pleno', 'relatorios.exportar'),
        ('tecnico_pleno', 'relatorios.visualizar'),
        ('tecnico_pleno', 'sessao.configuracoes.acessar'),
        ('tecnico_pleno', 'sessao.drive.acessar'),
        ('tecnico_pleno', 'sessao.gestao.acessar'),
        ('tecnico_pleno', 'sessao.treinamentos.acessar'),
        ('tecnico_pleno', 'usuarios.alterar_email'),
        ('tecnico_pleno', 'usuarios.alterar_perfil'),
        ('tecnico_pleno', 'usuarios.ativar'),
        ('tecnico_pleno', 'usuarios.bloquear'),
        ('tecnico_pleno', 'usuarios.criar'),
        ('tecnico_pleno', 'usuarios.desativar'),
        ('tecnico_pleno', 'usuarios.desbloquear'),
        ('tecnico_pleno', 'usuarios.editar'),
        ('tecnico_pleno', 'usuarios.excluir'),
        ('tecnico_pleno', 'usuarios.redefinir_senha'),
        ('tecnico_pleno', 'usuarios.ver_logs'),
        ('tecnico_pleno', 'usuarios.visualizar'),
        ('tecnico_senior', 'configuracoes.editar'),
        ('tecnico_senior', 'configuracoes.visualizar'),
        ('tecnico_senior', 'dashboard.visualizar'),
        ('tecnico_senior', 'documentos_biblioteca.editar'),
        ('tecnico_senior', 'documentos_biblioteca.visualizar'),
        ('tecnico_senior', 'inicio.visualizar'),
        ('tecnico_senior', 'lgpd.anonimizar'),
        ('tecnico_senior', 'lgpd.configurar'),
        ('tecnico_senior', 'lgpd.exportar_dados'),
        ('tecnico_senior', 'logs.exportar'),
        ('tecnico_senior', 'logs.visualizar'),
        ('tecnico_senior', 'mural.criar'),
        ('tecnico_senior', 'mural.editar'),
        ('tecnico_senior', 'mural.excluir'),
        ('tecnico_senior', 'mural.visualizar'),
        ('tecnico_senior', 'notificacoes.configurar'),
        ('tecnico_senior', 'notificacoes.visualizar'),
        ('tecnico_senior', 'onboarding.concluir_proprio'),
        ('tecnico_senior', 'onboarding.editar'),
        ('tecnico_senior', 'onboarding.visualizar'),
        ('tecnico_senior', 'operacoes.editar'),
        ('tecnico_senior', 'operacoes.visualizar'),
        ('tecnico_senior', 'relatorios.exportar'),
        ('tecnico_senior', 'relatorios.visualizar'),
        ('tecnico_senior', 'sessao.configuracoes.acessar'),
        ('tecnico_senior', 'sessao.drive.acessar'),
        ('tecnico_senior', 'sessao.gestao.acessar'),
        ('tecnico_senior', 'sessao.treinamentos.acessar'),
        ('tecnico_senior', 'usuarios.alterar_email'),
        ('tecnico_senior', 'usuarios.alterar_perfil'),
        ('tecnico_senior', 'usuarios.ativar'),
        ('tecnico_senior', 'usuarios.bloquear'),
        ('tecnico_senior', 'usuarios.criar'),
        ('tecnico_senior', 'usuarios.desativar'),
        ('tecnico_senior', 'usuarios.desbloquear'),
        ('tecnico_senior', 'usuarios.editar'),
        ('tecnico_senior', 'usuarios.excluir'),
        ('tecnico_senior', 'usuarios.redefinir_senha'),
        ('tecnico_senior', 'usuarios.ver_logs'),
        ('tecnico_senior', 'usuarios.visualizar'),
        ('analista_ti', 'configuracoes.editar'),
        ('analista_ti', 'configuracoes.visualizar'),
        ('analista_ti', 'dashboard.visualizar'),
        ('analista_ti', 'documentos_biblioteca.editar'),
        ('analista_ti', 'documentos_biblioteca.visualizar'),
        ('analista_ti', 'inicio.visualizar'),
        ('analista_ti', 'lgpd.anonimizar'),
        ('analista_ti', 'lgpd.configurar'),
        ('analista_ti', 'lgpd.exportar_dados'),
        ('analista_ti', 'logs.exportar'),
        ('analista_ti', 'logs.visualizar'),
        ('analista_ti', 'mural.criar'),
        ('analista_ti', 'mural.editar'),
        ('analista_ti', 'mural.excluir'),
        ('analista_ti', 'mural.visualizar'),
        ('analista_ti', 'notificacoes.configurar'),
        ('analista_ti', 'notificacoes.visualizar'),
        ('analista_ti', 'onboarding.concluir_proprio'),
        ('analista_ti', 'onboarding.editar'),
        ('analista_ti', 'onboarding.visualizar'),
        ('analista_ti', 'operacoes.editar'),
        ('analista_ti', 'operacoes.visualizar'),
        ('analista_ti', 'relatorios.exportar'),
        ('analista_ti', 'relatorios.visualizar'),
        ('analista_ti', 'sessao.configuracoes.acessar'),
        ('analista_ti', 'sessao.drive.acessar'),
        ('analista_ti', 'sessao.gestao.acessar'),
        ('analista_ti', 'sessao.treinamentos.acessar'),
        ('analista_ti', 'usuarios.alterar_email'),
        ('analista_ti', 'usuarios.alterar_perfil'),
        ('analista_ti', 'usuarios.ativar'),
        ('analista_ti', 'usuarios.bloquear'),
        ('analista_ti', 'usuarios.criar'),
        ('analista_ti', 'usuarios.desativar'),
        ('analista_ti', 'usuarios.desbloquear'),
        ('analista_ti', 'usuarios.editar'),
        ('analista_ti', 'usuarios.excluir'),
        ('analista_ti', 'usuarios.redefinir_senha'),
        ('analista_ti', 'usuarios.ver_logs'),
        ('analista_ti', 'usuarios.visualizar')
    ) AS v (id_perfil, chave)
    WHERE EXISTS (SELECT 1 FROM dbo.perfis p WHERE p.id_perfil = v.id_perfil)
      AND EXISTS (SELECT 1 FROM dbo.permissoes x WHERE x.chave = v.chave)
      AND NOT EXISTS (SELECT 1 FROM dbo.perfil_permissoes e WHERE e.id_perfil = v.id_perfil AND e.chave_permissao = v.chave);
END;
